{
    "main_area": [
        [
            24,
            454
        ],
        [
            16,
            19
        ],
        [
            615,
            27
        ],
        [
            618,
            464
        ]
    ],
    "parking_lot": [
        [
            [
                18,
                31
            ],
            [
                113,
                23
            ],
            [
                115,
                151
            ],
            [
                30,
                150
            ]
        ],
        [
            [
                165,
                28
            ],
            [
                164,
                152
            ],
            [
                263,
                155
            ],
            [
                254,
                27
            ]
        ],
        [
            [
                323,
                29
            ],
            [
                326,
                154
            ],
            [
                402,
                148
            ],
            [
                385,
                39
            ]
        ],
        [
            [
                435,
                39
            ],
            [
                454,
                155
            ],
            [
                557,
                155
            ],
            [
                539,
                43
            ]
        ],
        [
            [
                40,
                187
            ],
            [
                37,
                372
            ],
            [
                146,
                359
            ],
            [
                141,
                184
            ]
        ],
        [
            [
                181,
                196
            ],
            [
                191,
                323
            ],
            [
                261,
                319
            ],
            [
                270,
                185
            ]
        ],
        [
            [
                338,
                199
            ],
            [
                345,
                330
            ],
            [
                436,
                334
            ],
            [
                413,
                207
            ]
        ],
        [
            [
                466,
                207
            ],
            [
                483,
                341
            ],
            [
                608,
                343
            ],
            [
                571,
                225
            ]
        ]
    ]
}